{% set name = "regions" %}
{% set version = "0.4" %}
{% set hash_type = "sha256" %}
{% set hash_value = "cc301146ac975cc91577c8fbf8c8ceb60c3011e09607f0f1e65b7e1fdd6534bd" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.tar.gz'
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  '{{ hash_type }}': '{{ hash_value }}'

build:
  number: 0
  script: python setup.py install --offline --single-version-externally-managed --record=record.txt

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - numpy
    - setuptools
  run:
    - python
    - six
    - {{ pin_compatible('numpy') }}
    - astropy

test:
  imports:
    - regions
    - regions.core
    - regions.io
    - regions.shapes

about:
  home: https://github.com/astropy/regions
  license: BSD 3-clause
  license_file: LICENSE.rst
  license_family: BSD
  summary: Astropy affilated package for region handling
  description: |
    This is an in-development package for region handling based on Astropy.
    The goal is to merge the functionality from pyregion and photutils
    apertures and then after some time propose this package for inclusion in
    the Astropy core.
  doc_url: https://astropy-regions.readthedocs.io
  dev_url: https://github.com/astropy/regions

extra:
  recipe-maintainers:
    - mwcraig
    - bsipocz
    - cdeil
